version: 2

sources:
  - name: airbnb
    schema: raw
    tables:
      - name: listings
        identifier: raw_listings
        columns:
          - name: room_type
          - name: price
      - name: hosts
        identifier: raw_hosts
      - name: reviews
        identifier: raw_reviews

models:
  - name: airbnb
    schema:
    tables:
      - name: src_listings
      - name: src_listings
      - name: src_reviews
